services:
  - type: web
    name: smit-polra
    env: node
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGINS
        value: https://smit-polra.onrender.com,https://my-portfolio-tan-seven-73.vercel.app
      - key: DATA_DIR
        value: /opt/render/project/src/backend/data
    disk:
      name: smit-polra-data
      mountPath: /opt/render/project/src/backend/data
      sizeGB: 1
